name: Reboot VM

on:
  repository_dispatch:
    types: [reboot-vm]

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Reboot VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo reboot'

      - name: Clean up
        if: always()
        run: rm -f ~/.ssh/id_rsa
